INSERT INTO playlist_joe101 (artist, song, genre, year) values ('Aerosmith', "Janie's Got A Gun", "blues-rock", "1989");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ('Jack Johnson', "Brushfire Fairytales", "rock", "2000");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ('Gorillaz', "Rock The House", "hip hop", "2001");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ('Fruko Y Sus Tesos', "A La Memoria Del Muerto", "salsa", "2004");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Lily Allen", "Everyone's At It", "ska", "2009");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("3 Doors Down", "Here Without You", "post-grunge", "2002");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("3 Doors Down", "It's Not Me", "post-grunge", "2003");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("30 Seconds To Mars", "Year Zero", "rock", "2002");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Led Zeppelin", "Immigrant Song (Album Version)", "blues-rock", "1970");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("The Killers", "A Dustland Fairytale", "rock", "2008");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Yellowcard", "One Year_ Six Months", "rock", "2003");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Whitesnake", "Fool For Your Loving", "blues-rock", "1980");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("The B-52's", "Wig", "dance rock", "1986");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Sex Pistols", "Pretty Vacant", "punk", "1977");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("A Tribe Called Quest", "Scenario", "jazz rap", "1991");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Pete Rock & C.L. Smooth", "They Reminisce Over You (Single Version)", "jazz rap", "1992");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Eminem", "The Way I Am", "hip hop", "2000");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Eminem", "Just Don't Give A Fuck", "hip hop", "1998");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Eminem", "I'm Back", "hip hop", "2000");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Gorillaz", "Rock The House (Explicit)", "hip hop", "2001");
INSERT INTO playlist_joe101 (artist, song, genre, year) values ("Kanye West", "Street Lights", "hip hop", "2008");



INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("Gorillaz", "Rock The House (Explicit)", "hip hop", "2001");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("Kanye West", "Street Lights", "hip hop", "2008");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("Led Zeppelin", "Immigrant Song (Album Version)", "blues-rock", "1970");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("The Killers", "A Dustland Fairytale", "rock", "2008");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("Yellowcard", "One Year_ Six Months", "rock", "2003");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("Whitesnake", "Fool For Your Loving", "blues-rock", "1980");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("The B-52's", "Wig", "dance rock", "1986");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("Sex Pistols", "Pretty Vacant", "punk", "1977");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("A Tribe Called Quest", "Scenario", "jazz rap", "1991");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("Pete Rock & C.L. Smooth", "They Reminisce Over You (Single Version)", "jazz rap", "1992");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("Eminem", "The Way I Am", "hip hop", "2000");
INSERT INTO playlist_andrewdalba (artist, song, genre, year) values ("Eminem", "Just Don't Give A Fuck", "hip hop", "1998");


INSERT INTO playlist_chris123 (artist, song, genre, year) values ("Whitesnake", "Fool For Your Loving", "blues-rock", "1980");
INSERT INTO playlist_chris123 (artist, song, genre, year) values ("A Tribe Called Quest", "Scenario", "jazz rap", "1991");
INSERT INTO playlist_chris123 (artist, song, genre, year) values ("3 Doors Down", "Here Without You", "post-grunge", "2002");
INSERT INTO playlist_chris123 (artist, song, genre, year) values ("3 Doors Down", "It's Not Me", "post-grunge", "2003");
INSERT INTO playlist_chris123 (artist, song, genre, year) values ('Gorillaz', "Rock The House", "hip hop", "2001");


INSERT INTO playlist_slash (artist, song, genre, year) values ("Gorillaz", "Rock The House (Explicit)", "hip hop", "2001");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Kanye West", "Street Lights", "hip hop", "2008");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Led Zeppelin", "Immigrant Song (Album Version)", "blues-rock", "1970");
INSERT INTO playlist_slash (artist, song, genre, year) values ("The Killers", "A Dustland Fairytale", "rock", "2008");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Yellowcard", "One Year_ Six Months", "rock", "2003");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Whitesnake", "Fool For Your Loving", "blues-rock", "1980");
INSERT INTO playlist_slash (artist, song, genre, year) values ("The B-52's", "Wig", "dance rock", "1986");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Sex Pistols", "Pretty Vacant", "punk", "1977");
INSERT INTO playlist_slash (artist, song, genre, year) values ("A Tribe Called Quest", "Scenario", "jazz rap", "1991");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Pete Rock & C.L. Smooth", "They Reminisce Over You (Single Version)", "jazz rap", "1992");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Eminem", "The Way I Am", "hip hop", "2000");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Eminem", "Just Don't Give A Fuck", "hip hop", "1998");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Death From Above 1979", "Romantic Rights", "indie rock", "2004");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Snow Patrol", "Wow", "indie rock", "2003");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Snow Patrol", "In My Arms", "indie rock", "2006");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Snow Patrol", "Half The Fun", "indie rock", "2004");
INSERT INTO playlist_slash (artist, song, genre, year) values ("Snow Patrol", "Just Say Yes", "indie rock", "2009");
INSERT INTO playlist_slash (artist, song, genre, year) values ("The Strokes", "Between Love & Hate", "indie rock", "2003");
INSERT INTO playlist_slash (artist, song, genre, year) values ("The Strokes", "Meet Me In The Bathroom", "indie rock", "2003");


INSERT INTO playlist_blondie202 (artist, song, genre, year) values ('Aerosmith', "Janie's Got A Gun", "blues-rock", "1989");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ('Jack Johnson', "Brushfire Fairytales", "rock", "2000");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ('Gorillaz', "Rock The House", "hip hop", "2001");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ('Fruko Y Sus Tesos', "A La Memoria Del Muerto", "salsa", "2004");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Lily Allen", "Everyone's At It", "ska", "2009");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("3 Doors Down", "Here Without You", "post-grunge", "2002");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("3 Doors Down", "It's Not Me", "post-grunge", "2003");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("30 Seconds To Mars", "Year Zero", "rock", "2002");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Led Zeppelin", "Immigrant Song (Album Version)", "blues-rock", "1970");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("The Killers", "A Dustland Fairytale", "rock", "2008");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Yellowcard", "One Year_ Six Months", "rock", "2003");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Whitesnake", "Fool For Your Loving", "blues-rock", "1980");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("The B-52's", "Wig", "dance rock", "1986");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Sex Pistols", "Pretty Vacant", "punk", "1977");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("A Tribe Called Quest", "Scenario", "jazz rap", "1991");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Pete Rock & C.L. Smooth", "They Reminisce Over You (Single Version)", "jazz rap", "1992");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Eminem", "The Way I Am", "hip hop", "2000");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Eminem", "Just Don't Give A Fuck", "hip hop", "1998");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Eminem", "I'm Back", "hip hop", "2000");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Gorillaz", "Rock The House (Explicit)", "hip hop", "2001");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Kanye West", "Street Lights", "hip hop", "2008");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Auf Der Maur", "Taste You", "post-grunge", "2004");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Blue October", "Blue Skies", "post-grunge", "2009");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Cake", "Arco Arena", "post-grunge", "2001");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("David Cook", "I Did it for You", "post-grunge", "2008");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Dishwalla", "Moisture", "post-grunge", "1995");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Lit", "Lovely Day", "post-grunge", "1999");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Motograter", "Red (Main Version)", "post-grunge", "2003");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Semisonic", "Secret Smile", "post-grunge", "1998");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Sick Puppies", "Master Of The Universe", "post-grunge", "2009");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Silverchair", "The Door", "post-grunge", "1997");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Sister Hazel", "Think About Me", "post-grunge", "1997");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("Strata", "Night Falls (The Weight Of It)", "post-grunge", "2007");
INSERT INTO playlist_blondie202 (artist, song, genre, year) values ("The Exies", "Creeper Kamikaze", "post-grunge", "2003");